microsoft/Partner-Center-PowerShell

- README.md
> Updates to the read me file.

- src/PowerShell/Commands/GetPartnerCustomerAgreement.cs
- src/PowerShell/Commands/PartnerPSCmdlet.cs
- src/PowerShell/Commands/TestPartnerDomainAvailability.cs
- src/PowerShell/Exceptions/PartnerPSException.cs
- src/PowerShell/PowerShell.csproj
- src/PowerShell/Validations/AddressValidator.cs
- test/PowerShell.Tests/Validations/AddressValidatorTests.cs
Added the ability to extract additional error details
> Added the ability to extract additional error details

- docs/help/Get-PartnerCustomerSubscriptionUtilization.md
- src/PowerShell/Commands/GetPartnerCustomerDevice.cs
- src/PowerShell/Commands/GetPartnerCustomerSubscriptionUtilization.cs
- test/PowerShell.Tests/Commands/CustomerTests.cs
- test/PowerShell.Tests/Commands/CustomerTests.ps1
- test/PowerShell.Tests/PowerShell.Tests.csproj
- test/PowerShell.Tests/SessionRecords/GetUtilizationRecords.json
Addressed issue with data validation parameter
> Addressed issue with date validation

- README.md
Through this pull request a minor change to the read me document was made.
> Updated the read me document

- src/PowerShell/Commands/ConnectPartnerCenter.cs
- src/PowerShell/PowerShell.csproj
Added logic to set the Partner Center client type to Partner Center PowerShell
> Added logic to set the Partner Center client type.

- docs/help/New-PartnerAccessToken.md
- docs/help/Set-PartnerCustomerSubscription.md
- src/Core.Models/Core.Models.csproj
- src/Core/Core.csproj
- src/PowerShell/Commands/ConnectPartnerCenter.cs
- src/PowerShell/Commands/GetPartnerCustomerSubscription.cs
- src/PowerShell/Commands/NewPartnerAccessToken.cs
- src/PowerShell/Commands/SetPartnerCustomerSubscription.cs
Through this pull request the following changes are being made
1. Added the ability to modify the billing cycle for a subscription
2. Added version information to the new libraries
3. Corrected a minor typo 
4. Updated help documentation
> Added the ability to change a subscriptions billing cycle.

- src/PowerShell/PartnerCenter.psd1
> Updated the release notes.

- src/PartnerCenter.TestFramework/Network/HttpMockHandler.cs
- src/PartnerCenter.TestFramework/Network/HttpResponseRecords.cs
- src/PowerShell/Authentication/AuthenticationConstants.cs
- src/PowerShell/Commands/ConnectPartnerCenter.cs
- src/PowerShell/Commands/NewPartnerAccessToken.cs
- src/PowerShell/Factories/AuthenticationFactory.cs
- src/PowerShell/Properties/Resources.Designer.cs
- src/PowerShell/Properties/Resources.resx
Through this pull request the following changes are being made 
1. Added debug statements to the Connect-PartnerCenter command
2. Added debug statements to the authentication factory
3. Consolidated authentication constants into a single class
4. Refactored how responses were handled by the test framework
> Authentication and test updates

- docs/help/New-PartnerAccessToken.md
- docs/help/PartnerCenter.md
- src/PowerShell/Commands/ConnectPartnerCenter.cs
- src/PowerShell/Commands/NewPartnerAccessToken.cs
Through this pull request the following changes are being made
1. Added alias for the environment parameter
2. Addressed a parameters cannot be resolved issue.
3. Updated the documentation.
Docs issue [#30](https://github.com/MicrosoftDocs/partner-center-docs-powershell/issues/30)
> Addressed parameter set cannot be resolved issue

- docs/help/Connect-PartnerCenter.md
Through this pull request the documentation for the `Connect-PartnerCenter` command is being updated.
Docs issue [#30](https://github.com/MicrosoftDocs/partner-center-docs-powershell/issues/30)
> Updates to the Connect-PartnerCenter command documentation.

- src/PowerShell/Factories/AuthenticationFactory.cs
Through this pull request the default logging for ADAL will be disabled.
> Configured ADAL to not use default logging.

- docs/help/New-PartnerCustomer.md
- docs/help/New-PartnerCustomerAgreement.md
- docs/help/Set-PartnerCustomer.md
- src/PowerShell/Commands/NewPartnerCustomer.cs
- src/PowerShell/Commands/NewPartnerCustomerAgreement.cs
- src/PowerShell/Commands/SetPartnerCustomer.cs
Trying to fix grammar for multiple parameters descriptions to make them a little easier to understand.
> fixing parameters desciptions to match the desired effect - grammar

- ChangeLog.md
- azure-pipelines.yml
- build/PartnerCenter.NetCore.nuspec
- build/PartnerCenter.nuspec
- src/PartnerCenter.TestFramework/GlobalSuppressions.cs
- src/PartnerCenter.TestFramework/Network/HttpUtilities.cs
- src/PartnerCenter.TestFramework/PartnerCenter.TestFramework.csproj
- src/PartnerCenter/Models/Auditing/OperationType.cs
- src/PartnerCenter/PartnerCenter.csproj
- src/PowerShell/Commands/GetPartnerCustomerSubscriptionUtilization.cs
- src/PowerShell/PowerShell.csproj
- test/PartnerCenter.Tests.Integration/PartnerCenter.Tests.Integration.csproj
- test/PartnerCenter.Tests.UnitTests/PartnerCenter.Tests.UnitTests.csproj
- test/PowerShell.Tests.UnitTests/PowerShell.Tests.UnitTests.csproj
Through this pull request the following changes are being made 
* Auditing
* Renamed the CreateInvoice operation type to ReadyInvoice
* Build 
* Added PowerShell tasks to the build process
> Auditing feature update

- ChangeLog.md
Through this pull request a minor update to the change log is being made.
> Change log update

- src/PowerShell/Factories/ClientFactory.cs
Through this pull request the way the delegating handlers are applied has been modified
> Modified the way the delegating handlers are applied

- docs/upcoming-breaking-changes.md
- src/PowerShell/Commands/NewPartnerCustomerAgreement.cs
Through this pull request a notice regarding the breaking change for the user identifier has been added.
> Agreement feature update

- docs/help/New-PartnerCustomerOrder.md
- src/PowerShell/Commands/NewPartnerCustomerOrder.cs
Added the ability to configure the billing cycle when creating new orders
#123
> Added the billing cycle parameter

- ChangeLog.md
- src/PowerShell/Commands/GetPartnerCustomerSubscriptionUtilization.cs
- src/PowerShell/Commands/GetPartnerCustomerUser.cs
- src/PowerShell/Commands/NewPartnerCustomerUser.cs
- src/PowerShell/Commands/SetPartnerCustomerUser.cs
- src/PowerShell/Models/Users/PSCustomerUser.cs
Through this pull request the following properties are being added to the user model
* ImmutableId
* PhoneNumber
#30
> User model updates

- src/PowerShell/Attributes/BreakingChangeBaseAttribute.cs
- src/PowerShell/Authentication/AuthenticationTypes.cs
- src/PowerShell/Commands/GetPartnerProductSKU.cs
- src/PowerShell/Commands/PartnerPSCmdlet.cs
- src/PowerShell/Commands/SetPartnerCustomerUserLicense.cs
- src/PowerShell/Models/Customers/PSCustomerBillingProfile.cs
- src/PowerShell/Models/Licenses/PSLicenseUpdate.cs
- src/PowerShell/Models/Users/PSCustomerUser.cs
- src/PowerShell/PowerShell.csproj
Through this pull request the following changes are being made
- Minor code cleanup
- Updated the Partner Center nuget package
> Feature update

- docs/help/PartnerCenter.md
Through this pull request the help documentation is being updated
> Updating the help documentation

- src/PowerShell/PowerShell.csproj
Through this pull request the version of Microsoft.Rest.ClientRuntime is being updated
#153
> Updating to the latest version of Microsoft.Rest.ClientRuntime

- docs/help/Connect-PartnerCenter.md
- docs/help/PartnerCenter.md
- docs/help/Test-PartnerSecurityRequirement.md
- src/PowerShell/Commands/ConnectPartnerCenter.cs
- src/PowerShell/Commands/TestPartnerSecurityRequirement.cs
- src/PowerShell/PartnerCenter.psd1
Through this pull request the enforce MFA parameter is added and the ability to test the current partner security requirements for a specific account
> Command and documentation update

- docs/help/Connect-PartnerCenter.md
Through this pull the documentation is being updated to address an issue with an example
#168
> Updating the documentation

- src/PowerShell/Models/Invoices/PSOneTimeInvoiceLineItem.cs
Through this pull request the billing provider frequency is being added
> Adding the billing frequency property

- ChangeLog.md
- src/PowerShell/Commands/GetPartnerUserSignInActivity.cs
- src/PowerShell/Commands/TestPartnerSecurityRequirement.cs
- src/PowerShell/PartnerCenter.psd1
- src/PowerShell/PowerShell.csproj
- test/PowerShell.UnitTests/PowerShell.UnitTests.csproj
Through this pull request test partner security requirement command is being updated.
> Test feature update

- ChangeLog.md
- src/PowerShell/Authenticators/DeviceCodeAuthenticator.cs
- src/PowerShell/Commands/GetPartnerUser.cs
- src/PowerShell/Commands/TestPartnerSecurityRequirement.cs
Through this pull request the issue preventing the generation of an access token when using device code flow is being addressed.
#186
> Authentication feature update

- src/PowerShell/Commands/GetPartnerCustomer.cs
Through this pull request the get customer command is being updated
> Updating the get customer command

- src/PowerShell/Commands/PartnerPSCmdlet.cs
- src/PowerShell/Models/PartnerQosEvent.cs
Through this pull request the ability to capture telemetry has been added.
> Adding the ability to capture telemetry

- src/PowerShell/Commands/PartnerPSCmdlet.cs
Through this pull request adding logic to ignore any error with capturing the telemetry
> Ignore any error with capturing the telemetry

- ChangeLog.md
Through this pull request the release notes are being updated 
> Updating the release notes

- src/PowerShell/Factories/ClientFactory.cs
- src/PowerShell/PartnerCenter.psd1
- src/PowerShell/PowerShell.csproj
- test/PowerShell.UnitTests/PowerShell.UnitTests.csproj
Through this pull request the delegating handler used to retry Microsoft Graph operations is being updated. 
#194
> Updating delegating handler

- ChangeLog.md
- docs/help/Connect-PartnerCenter.md
- docs/help/Enable-PartnerAzureSubscription.md
- docs/help/New-PartnerAzureSubscription.md
- docs/help/PartnerCenter.md
- docs/help/Suspend-PartnerAzureSubscription.md
- docs/upcoming-breaking-changes.md
- src/PowerShell/Commands/ConnectPartnerCenter.cs
- src/PowerShell/Commands/EnablePartnerAzureSubscription.cs
- src/PowerShell/Commands/NewPartnerAzureSubscription.cs
- src/PowerShell/Commands/SuspendPartnerAzureSubscription.cs
- src/PowerShell/PartnerCenter.psd1
Through this pull request the ability to enable or suspend an Azure subscription that is part of an Azure Plan is being added. 
#212
> Subscription feature update

- docs/upcoming-breaking-changes.md
- src/PowerShell/Commands/ConnectPartnerCenter.cs
- src/PowerShell/Commands/GetPartnerCustomer.cs
- src/PowerShell/Commands/GetPartnerCustomerSubscription.cs
- src/PowerShell/Commands/GetPartnerUser.cs
- src/PowerShell/Commands/GetPartnerUserSignInActivity.cs
- src/PowerShell/Factories/ClientFactory.cs
- src/PowerShell/Network/ClientTracingHandler.cs
Through this pull request the customer and user features are being updated
> Customer and user feature update

- docs/help/Get-PartnerUserSignInActivity.md
- src/PowerShell/Commands/GetPartnerUserSignInActivity.cs
Through this pull request the ability to get sign-in activities using batch processing is being added.
#194
> User feature update

- src/PowerShell/Commands/SuspendPartnerAzureSubscription.cs
- src/PowerShell/Factories/ClientFactory.cs
- src/PowerShell/Models/Authentication/IPartnerAccount.cs
- src/PowerShell/Models/Authentication/PartnerAccount.cs
Through this pull request I am updating the way partner account information is handled.
#228
> Client feature update

- ChangeLog.md
- src/PowerShell/Commands/EnablePartnerAzureSubscription.cs
- src/PowerShell/Commands/SuspendPartnerAzureSubscription.cs
- src/PowerShell/PartnerCenter.psd1
- src/PowerShell/PowerShell.csproj
- src/Subscription/ISubscriptionsOperations.cs
- src/Subscription/SubscriptionsOperations.cs
- src/Subscription/SubscriptionsOperationsExtensions.cs
- test/PowerShell.UnitTests/PowerShell.UnitTests.csproj
Through this pull request the subscription feature is being updated 
#228
> Updating the subscription feature

- src/PowerShell/Authenticators/DelegatingAuthenticator.cs
- src/PowerShell/Authenticators/DeviceCodeAuthenticator.cs
- src/PowerShell/Authenticators/InteractiveUserAuthenticator.cs
- src/PowerShell/Authenticators/RefreshTokenAuthenticator.cs
- src/PowerShell/Authenticators/ServicePrincipalAuthenticator.cs
- src/PowerShell/Authenticators/SilentAuthenticator.cs
- src/PowerShell/Commands/ConnectPartnerCenter.cs
- src/PowerShell/Commands/NewPartnerAccessToken.cs
- src/PowerShell/Models/Authentication/ComponentKey.cs
- src/PowerShell/PartnerCenter.psd1
- src/PowerShell/PowerShell.csproj
- src/PowerShell/Utilities/IPartnerTokenCache.cs
- src/PowerShell/Utilities/InMemoryTokenCache.cs
- src/PowerShell/Utilities/PersistentTokenCache.cs
Through a pull request the way the token cache is managed is being updated.
#234
> Updating the way the token cache is managed

- ChangeLog.md
- docs/help/Get-PartnerInvoiceLineItem.md
- docs/help/Get-PartnerUnbilledInvoiceLineItem.md
- docs/help/PartnerCenter.md
- src/PowerShell/Commands/GetPartnerInvoiceLineItem.cs
- src/PowerShell/Commands/GetPartnerUnbilledInvoiceLineItems.cs
- src/PowerShell/PartnerCenter.psd1
Through this pull request the operations for the unbilled invoice line items are being simplified. 
> Simplifying the unbilled invoice line item operations

- docs/help/Get-PartnerUnbilledInvoiceLineItem.md
- src/PowerShell/Commands/GetPartnerInvoiceLineItem.cs
- src/PowerShell/Network/SingleMessageTcpListener.cs
Updating the invoice feature to ensure requests are using the correct route
> Invoice feature update

- CHANGELOG.md
- test/PowerShell.UnitTests/PowerShell.UnitTests.csproj
Through this pull request the change log and version information is being updated
> Updating the change log and version

- src/PowerShell/Commands/NewPartnerAccessToken.cs
Through this pull request the way the account is populated is being updated
[#93](https://github.com/MicrosoftDocs/partner-center-docs-powershell/issues/93)
> Updating the way the account is populated

- CHANGELOG.md
Through this pull request the change log is being updated
> Updating the change log

- CHANGELOG.md
- src/PowerShell/Models/DevicesDeployment/PSDevice.cs
Through this pull request the device model is being updated to ensure the policies property is populated.
#271
> Updating the device model

- src/PowerShell/Microsoft.Store.PartnerCenter.PowerShell.format.ps1xml
Through this pull request the device batch output format is being corrected
#281
> Updating the formatting for a device batch

- CHANGELOG.md
- src/Billing/Billing.csproj
- src/PowerShell/PartnerCenter.psd1
- src/Subscription/Subscription.csproj
Through this pull request the way the module is loaded is being updated
#261
> Updating the way the module is loaded

- azure-pipelines.yml
- test/PowerShell.UnitTests/PowerShell.UnitTests.csproj
Through this pull request the PowerShell reference for the test project is being updated
> Updating the PowerShell reference for the test project

- CHANGELOG.md
- src/PowerShell/Commands/GetPartnerCustomerUser.cs
- src/PowerShell/Commands/PartnerPSCmdlet.cs
- src/PowerShell/PartnerCenter.psd1
- src/PowerShell/PowerShell.csproj
- src/PowerShell/Properties/launchSettings.json
Through this pull request the way customer users are returned is being updated
#290
> Addressing an issue with the customer users functionality

- azure-pipelines.yml
- src/PowerShell/PowerShell.csproj
Through this pull request the build configuration is being updated
#295 #300
> Updating the build configuration

- azure-pipelines.yml
- build.proj
Through this pull request the build pipeline is being updated
N/A
> Build pipeline updates
